[package]
name = "advent2020"
description = "Solutions to Advent of Code 2020"
version = "0.1.0"
authors = ["Kesavan Yogeswaran <kesyog@gmail.com>"]
edition = "2018"

[dependencies]
num-integer = "0.1"
regex = "1"
utils = { path = "../utils" }

[[bin]]
name = "2020-day1"
path = "src/day1.rs"
