[package]
name = "utils"
description = "General utility functions for solving Advent of Code problems"
version = "0.1.0"
authors = ["Kesavan Yogeswaran <kesyog@gmail.com>"]
edition = "2021"

[dependencies]
derive_more = "0.99"
nom = "7"
num-complex = "0.4"
num-integer = "0.1"
regex = "1"
