name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
          components: clippy, rustfmt
    - name: rustfmt
      uses: mbrobbel/rustfmt-check@0.7.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: cargo test --verbose
    # Can't build since the main build depends on test inputs, which cannot be committed to the repo
    # per Advent of Code policy
