name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          components: rustfmt
          override: true
    - name: rustfmt
      uses: mbrobbel/rustfmt-check@0.3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
